namespaced-key: "carved_spruce_planks"
block-settings:
  dig-speed: 11.0
  drop:
    experience: 0
    drops-default-item: true
  tool:
    type: AXE
    force: false
item:
  material: PAPER
  name: "Резные еловые доски"
  custom-model-data: 13024
craft:
  show-in-crafts-menu: true
  group: "carved_planks"
  shaped-recipe:
    - "S"
    - "S"
  material-list:
    S: SPRUCE_SLAB
placing:
  normal:
    instrument: BANJO
    note: 24
    is-powered: false
sounds:
  place:
    sound-name: "block.wood.place"
    sound-category: BLOCKS
    pitch: 1.0
    volume: 1.0
  break:
    sound-name: "block.wood.break"
    sound-category: BLOCKS
    pitch: 1.0
    volume: 1.0
  step:
    sound-name: "block.wood.step"
    sound-category: PLAYERS
    pitch: 0.9
    volume: 0.3
  hit:
    sound-name: "block.wood.hit"
    sound-category: BLOCKS
    pitch: 0.5
    volume: 0.5