namespaced-key: "vertical_mangrove_planks"
block-settings:
  dig-speed: 11.0
  drop:
    experience: 0
    drops-default-item: true
  tool:
    type: AXE
    force: false
item:
  material: PAPER
  name: "Вертикальные мангровые доски"
  custom-model-data: 13008
craft:
  show-in-crafts-menu: true
  group: "vertical_planks"
  shaped-recipe:
    - "P"
    - "P"
    - "P"
  material-list:
    P: MANGROVE_PLANKS
  item-amount: 3
placing:
  normal:
    instrument: BANJO
    note: 8
    is-powered: false
sounds:
  place:
    sound-name: "block.wood.place"
    sound-category: BLOCKS
    pitch: 1.0
    volume: 1.0
  break:
    sound-name: "block.wood.break"
    sound-category: BLOCKS
    pitch: 1.0
    volume: 1.0
  step:
    sound-name: "block.wood.step"
    sound-category: PLAYERS
    pitch: 0.9
    volume: 0.3
  hit:
    sound-name: "block.wood.hit"
    sound-category: BLOCKS
    pitch: 0.5
    volume: 0.5