name: $name
version: $version
description: $description
authors: [ $authors ]
contributors: [ $contributors ]
website: $website

main: $main
api-version: $apiVersion
dependencies:
  - name: MSCore
    version: $version
  - name: MSItem
    version: $version
  - name: MSDecor
    version: $version
  - name: MSEssentials
    version: $version
  - name: CoreProtect
    version: 21.3
  - name: ProtocolLib
    version: 5.0.0
load-after:
  - name: CoreProtect
  - name: ProtocolLib