namespaced-key: "purple_lightsaber"
rename-text: "Фиолетовый световой меч"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 13
show-in-rename-menu: true