namespaced-key: "purple_lightsaber_dual"
rename-text: "Двойной фиолетовый световой меч"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 14
show-in-rename-menu: true