namespaced-key: "yellow_lightsaber_dual"
rename-text: "Двойной жёлтый световой меч"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 18
show-in-rename-menu: true