namespaced-key: "yellow_lightsaber"
rename-text: "Жёлтый световой меч"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 17
show-in-rename-menu: true