namespaced-key: "blue_lightsaber"
rename-text: "Синий световой меч"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 9
show-in-rename-menu: true