namespaced-key: "green_lightsaber"
rename-text: "Зелёный световой меч"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 11
show-in-rename-menu: true