namespaced-key: "green_lightsaber_dual"
rename-text: "Двойной зелёный световой меч"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 12
show-in-rename-menu: true