namespaced-key: "red_lightsaber"
rename-text: "Красный световой меч"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 15
show-in-rename-menu: true