namespaced-key: "jailors_scythe"
rename-text: "Смертельная коса"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 6
show-in-rename-menu: true