#file: noinspection YAMLSchemaValidation
name: $name
version: $version
description: $description
authors: [ $authors ]
contributors: [ $contributors ]
website: $website

main: $main
api-version: $apiVersion
dependencies:
  - name: MSEssentials
    version: $version
  - name: MSItem
    version: $version
  - name: MSDecor
    version: $version
  - name: MSBlock
    version: $version
  - name: CoreProtect
    version: '22.2'
load-after:
  - name: CoreProtect
load-before:
  - name: MSEssentials
  - name: MSBlock
  - name: MSItem
  - name: MSDecor
