namespaced-key: "golem_gauntlet"
rename-text: "Устарелый големский кулак"
material: 
  - WOODEN_AXE
  - STONE_AXE
  - IRON_AXE
  - GOLDEN_AXE
  - DIAMOND_AXE
  - NETHERITE_AXE
custom-model-data: 2
show-in-rename-menu: true