namespaced-key: "hammer_of_gravity"
rename-text: "Гравитационный молот"
material: 
  - WOODEN_AXE
  - STONE_AXE
  - IRON_AXE
  - GOLDEN_AXE
  - DIAMOND_AXE
  - NETHERITE_AXE
custom-model-data: 4
show-in-rename-menu: true