name: Build
on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Build
        run: ./gradlew build --no-daemon --stacktrace
        
