namespaced-key: "breche_katana"
rename-text: "Самурайская катана"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 1
show-in-rename-menu: true