namespaced-key: "frostscythe"
rename-text: "Морозная коса"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 4
show-in-rename-menu: true