namespaced-key: "masters_katana"
rename-text: "Огненная катана"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 7
show-in-rename-menu: true