namespaced-key: "pirate_hook"
rename-text: "Пиратский крюк"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 8
show-in-rename-menu: true